wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_ANKYLOGLOSSIA.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_APVR.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_ASD.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_AVSD.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CHROMOSOMAL_ABNORMALITI_NOT_ELSEW_CLASSIFIED.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CLEFT_AND_CARIES.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CLEFT_HARD_PALATE_NOS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CLEFT_LIP.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CLEFT_LIP_CLEFT_PALATE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CLEFT_LIP_OR_LIP_AND_PALATE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CLEFT_PALATE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_COMPLEX_CARD_DEFEC.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_DEFORMITI_FEET.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_DEFORMITI_HIP.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_ICHTHYOSIS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_LENS_MALFO.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_ANTER_SEGMENT_EYE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_BILI.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_BREAST.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_CARDIAC_CHAMB_CONNECTIO.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_CIRCULATO_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_DEFORMAT_MUSCULOS_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_EAR_CAUSI_IMPAIRM_HEARING.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_EYELID_LACRIMAL_APPARA_ORBIT.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_EYE_EAR_FACE_NECK.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_GALLB_BILE_DUCTS_LIVER.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_GENITAL_ORGANS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_GREAT_ARTERIES.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_GREAT_VEINS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_LARYNX.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_LUNG.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_MUSCULOS_SYSTEM_NOT_ELSEW_CLASSIFIED.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_NERVOUS_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_NOSE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_OESOPHAGUS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_OVARIES_FALLOP_TUBES_BROAD_LIGAM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_POSTERI_SEGMENT_EYE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_PULMONARY_TRICU_VALVES.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_RESPI_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_RETI.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_SPINE_BONY_THORAX.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_TRACHEA_BRONCHUS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_URINARY_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MALFO_UTERUS_CERVIX.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_MUSCULOS_DEFORMITI_HEAD_FACE_SPINE_CHEST.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONGEN_OBSTRUCTIVE_DEFECTS_RENAL_PELVIS_CONGEN_MALFO_URETER.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CONOTR_DEFEC.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CRANIOSYNOSTOSIS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_CYSTIC_KIDNEY_DISEA.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_DOWNS_SYNDR.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_EHLER_SYNDR.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_HYPOSPADIAS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_LVOTO_BROAD.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_LVOTO_NARROW.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_MONOSOMI_DELET_AUTOSOMES_NOT_ELSEW_CLASSIFIED.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OSTEOCHONDROD_W_DEFECTS_GROWTH_TUBULAR_BONES_SPINE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CHROMOSOME_ABNORMALITI_NOT_ELSEW_CLASSIFIED.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_BRAIN.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_CIRCULATO_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_DIGES_SYSTEM1.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_DIGES_SYSTEM2.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_EAR.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_FACE_NECK.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_FEMALE_GENITALIA.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_HEART.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_INTESTINE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_KIDNEY.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_LIMBS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_MALE_GENITAL_ORGANS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_NERVOUS_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_NOT_ELSEW_CLASSIFIED.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_PERIP_VASCULAR_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_RESPI_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_SKIN.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_SKULL_FACE_BONES.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_TONGUE_MOUTH_PHARYNX.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_UPPER_ALIME_TRACT.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MALFO_URINARY_SYSTEM.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_CONGEN_MUSCULOS_DEFORMITI.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_OSTEOCHONDROD.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_SEX_CHROMOSOME_ABNORMALITI_MALE_PHENOT_NOT_ELSEW_CLASSIFIED.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_OTHER_SPECIFE_CONGEN_MALFO_SYNDR_AFFECTING_MULTIPLE_SYSTEMS.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_PDA.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_PHAKOMATOSES_NOT_ELSEW_CLASSIFIED.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_REDUCT_DEFECTS_LOWER_LIMB.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_REDUCT_DEFECTS_UPPER_LIMB.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_RENAL_AGENE_OTHER_REDUCT_DEFECTS_KIDNEY.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_RVOTO.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_SEPTA_DEFEC.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_SPINA_BIFIDA.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_SYNDACTYLY.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_UNDES_TESTICLE.gz
wget https://storage.googleapis.com/finngen-public-data-r11/summary_stats/finngen_R11_Q17_VACTREL.gz
